In [1]:
import numpy as np

In [ ]:
# array

In [2]:
x = [2,3,4,5,6]

In [3]:
np.array(x)

array([2, 3, 4, 5, 6])

In [5]:
array_x = np.array([4,5,6])

In [6]:
array_x

array([4, 5, 6])

In [7]:
type(array_x)

numpy.ndarray

In [ ]:
#ndim and shape

In [8]:
array_x.ndim

1

In [9]:
array_x.shape

(3,)

In [11]:
array_2d = np.array([[2,4,6,8],[1,3,5,7]])

In [12]:
array_2d

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [13]:
array_2d.ndim

2

In [14]:
array_2d.shape

(2, 4)

In [ ]:
# zeros, ones, empty

In [15]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
np.zeros((4,7))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [17]:
np.ones(13)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [18]:
np.ones((2,6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [20]:
arr_empty = np.empty((3,3,4))

In [21]:
arr_empty.ndim

3

In [22]:
arr_empty.shape

(3, 3, 4)

In [23]:
arr_empty

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [ ]:
# arange

In [24]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
np.arange(2,40,5)

array([ 2,  7, 12, 17, 22, 27, 32, 37])

In [ ]:
# Data Types for arrays

In [26]:
array_int = np.array([2,3,4,5], dtype = np.int32)
array_float = np.array([2,3,4,5], dtype = np.float64)

In [27]:
array_int

array([2, 3, 4, 5], dtype=int32)

In [28]:
array_float

array([ 2.,  3.,  4.,  5.])

In [29]:
array_float.dtype

dtype('float64')

In [ ]:
#astype

In [30]:
array1 = np.array([2,4,6,8,10])

In [31]:
array1

array([ 2,  4,  6,  8, 10])

In [32]:
array1.dtype

dtype('int64')

In [33]:
array1_float = array1.astype(np.float64)

In [34]:
array1_float

array([  2.,   4.,   6.,   8.,  10.])

In [35]:
array1_float.dtype

dtype('float64')

In [36]:
array_float = np.array([2.33, 3.4, 5.9, 4.23])

In [37]:
array_float

array([ 2.33,  3.4 ,  5.9 ,  4.23])

In [38]:
array_float.dtype

dtype('float64')

In [39]:
array_int = array_float.astype(np.int32)

In [40]:
array_int

array([2, 3, 5, 4], dtype=int32)

In [ ]:
# Operations on Arrays

In [41]:
array1 = np.array([[2,4,6],[1,3,5]])

In [42]:
array2 = np.array([[12,14,16],[13,15,17]])

In [44]:
array1 + array1

array([[ 4,  8, 12],
       [ 2,  6, 10]])

In [43]:
array1

array([[2, 4, 6],
       [1, 3, 5]])

In [45]:
array1 + array2

array([[14, 18, 22],
       [14, 18, 22]])

In [46]:
array2

array([[12, 14, 16],
       [13, 15, 17]])

In [47]:
array1 - array2

array([[-10, -10, -10],
       [-12, -12, -12]])

In [48]:
array2 - array2

array([[0, 0, 0],
       [0, 0, 0]])

In [49]:
array1 * array2

array([[24, 56, 96],
       [13, 45, 85]])

In [50]:
array1/array2

array([[0, 0, 0],
       [0, 0, 0]])

In [51]:
array1**0.5

array([[ 1.41421356,  2.        ,  2.44948974],
       [ 1.        ,  1.73205081,  2.23606798]])

# Indexing and Slicing Arrays

In [52]:
array1 = np.arange(15)

In [53]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
array1[7]

7

In [55]:
array1[-2]

13

In [56]:
array1 = np.arange(2,25,3)

In [57]:
array1

array([ 2,  5,  8, 11, 14, 17, 20, 23])

In [58]:
array1[4]

14

In [59]:
array1[2:5]

array([ 8, 11, 14])

In [63]:
array1[-2]

20

In [66]:
x = array1[2:5]

In [67]:
x

array([ 8, 11, 14])

In [68]:
x = 16

In [69]:
array1

array([ 2,  5,  8, 11, 14, 17, 20, 23])

# Indexing and Slicing Arrays

In [70]:
array1 = np.arange(14)

In [71]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [72]:
array1[3]

3

In [73]:
array1 = np.arange(2,35,3)

In [74]:
array1

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [75]:
array1[4]

14

In [76]:
array1[-3]

26

In [77]:
array1[3:7]

array([11, 14, 17, 20])

In [78]:
array1[3:7] = 16

In [79]:
array1

array([ 2,  5,  8, 16, 16, 16, 16, 23, 26, 29, 32])

In [80]:
array_slice = array1[3:7]

In [81]:
array_slice

array([16, 16, 16, 16])

In [82]:
array_slice[3] = 28

In [83]:
array1

array([ 2,  5,  8, 16, 16, 16, 28, 23, 26, 29, 32])

In [84]:
array_slice[1:3] = 123

In [85]:
array1

array([  2,   5,   8,  16, 123, 123,  28,  23,  26,  29,  32])

# Indexing and Slicing 2d Arrays

In [86]:
array2 = np.array([[2,4,6],[1,3,5],[22,23,34],[13,15,19]])

In [87]:
array2

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 23, 34],
       [13, 15, 19]])

In [88]:
array2.ndim

2

In [89]:
array2[0]

array([2, 4, 6])

In [90]:
array2[2]

array([22, 23, 34])

In [91]:
array2[-2]

array([22, 23, 34])

In [92]:
array2[0][1]

4

In [94]:
array2[3][0]

13

In [96]:
x = array2[3]

In [97]:
x

array([13, 15, 19])

In [98]:
x[0]

13

In [100]:
array2[2][1]

23

In [101]:
array2[2,1]

23

In [102]:
array2[1:3]

array([[ 1,  3,  5],
       [22, 23, 34]])

In [103]:
array2[2:3]

array([[22, 23, 34]])

In [104]:
array2[:3]

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 23, 34]])

In [105]:
array2

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 23, 34],
       [13, 15, 19]])

In [106]:
array2[:, 1:]

array([[ 4,  6],
       [ 3,  5],
       [23, 34],
       [15, 19]])

In [107]:
array2[:2, 1:]

array([[4, 6],
       [3, 5]])

In [108]:
array2[:2, :2]

array([[2, 4],
       [1, 3]])

In [109]:
array2[:, 1]

array([ 4,  3, 23, 15])

In [110]:
array2[:, 1:2]

array([[ 4],
       [ 3],
       [23],
       [15]])

In [112]:
array2[:2, :2] = 122

In [113]:
array2

array([[122, 122,   6],
       [122, 122,   5],
       [ 22,  23,  34],
       [ 13,  15,  19]])

# Boolean Indexing

In [123]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [124]:
states = np.array(['NY', 'DC','CA','NY','CA','DC','NY','CA'])

In [125]:
num = np.random.randn(8,4)

In [126]:
states

array(['NY', 'DC', 'CA', 'NY', 'CA', 'DC', 'NY', 'CA'], 
      dtype='|S2')

In [127]:
num

array([[ 0.36159562,  0.22688052,  0.02418903, -1.31330749],
       [-0.74025723, -0.85145899,  0.62497238, -0.38844124],
       [ 0.52265861, -1.21152343,  0.46556219, -1.22243406],
       [ 0.94164973, -0.09677378, -0.04441704, -0.01311397],
       [ 0.18613945,  0.12565582, -1.25519282,  0.87507717],
       [-1.13549505,  1.8419598 , -0.55614771,  0.50895742],
       [ 0.72030947,  2.35462602,  1.91604406,  1.6155526 ],
       [ 0.16048391, -0.09916628, -0.82619551,  0.81441685]])

In [128]:
num.shape

(8, 4)

In [129]:
states == 'NY'

array([ True, False, False,  True, False, False,  True, False], dtype=bool)

In [130]:
num[states == 'NY']

array([[ 0.36159562,  0.22688052,  0.02418903, -1.31330749],
       [ 0.94164973, -0.09677378, -0.04441704, -0.01311397],
       [ 0.72030947,  2.35462602,  1.91604406,  1.6155526 ]])

In [131]:
num[states == 'NY', 1:]

array([[ 0.22688052,  0.02418903, -1.31330749],
       [-0.09677378, -0.04441704, -0.01311397],
       [ 2.35462602,  1.91604406,  1.6155526 ]])

In [132]:
num[states == 'NY',1:3 ]

array([[ 0.22688052,  0.02418903],
       [-0.09677378, -0.04441704],
       [ 2.35462602,  1.91604406]])

In [133]:
num[states == 'NY', 0]

array([ 0.36159562,  0.94164973,  0.72030947])

In [134]:
num[states == 'NY', 0:1]

array([[ 0.36159562],
       [ 0.94164973],
       [ 0.72030947]])

In [ ]:
# == , ! = 

In [135]:
states != 'NY'

array([False,  True,  True, False,  True,  True, False,  True], dtype=bool)

In [136]:
states != 'DC'

array([ True, False,  True,  True,  True, False,  True,  True], dtype=bool)

In [138]:
num[~(states == 'NY')]

array([[-0.74025723, -0.85145899,  0.62497238, -0.38844124],
       [ 0.52265861, -1.21152343,  0.46556219, -1.22243406],
       [ 0.18613945,  0.12565582, -1.25519282,  0.87507717],
       [-1.13549505,  1.8419598 , -0.55614771,  0.50895742],
       [ 0.16048391, -0.09916628, -0.82619551,  0.81441685]])

In [ ]:
== ~ |

In [140]:
nydc = (states == 'NY') | (states == 'DC')

In [141]:
num[nydc]

array([[ 0.36159562,  0.22688052,  0.02418903, -1.31330749],
       [-0.74025723, -0.85145899,  0.62497238, -0.38844124],
       [ 0.94164973, -0.09677378, -0.04441704, -0.01311397],
       [-1.13549505,  1.8419598 , -0.55614771,  0.50895742],
       [ 0.72030947,  2.35462602,  1.91604406,  1.6155526 ]])

# Fancy Indexing !

In [ ]:
 - means indexing using int arrays

In [142]:
array1 = np.empty((12,5))

In [143]:
for x in range(12):
    array1[x] = x

In [144]:
array1

array([[  0.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,   1.,   1.],
       [  2.,   2.,   2.,   2.,   2.],
       [  3.,   3.,   3.,   3.,   3.],
       [  4.,   4.,   4.,   4.,   4.],
       [  5.,   5.,   5.,   5.,   5.],
       [  6.,   6.,   6.,   6.,   6.],
       [  7.,   7.,   7.,   7.,   7.],
       [  8.,   8.,   8.,   8.,   8.],
       [  9.,   9.,   9.,   9.,   9.],
       [ 10.,  10.,  10.,  10.,  10.],
       [ 11.,  11.,  11.,  11.,  11.]])

In [145]:
array1[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.]])

In [146]:
array1[[2,3,10,11]]

array([[  2.,   2.,   2.,   2.,   2.],
       [  3.,   3.,   3.,   3.,   3.],
       [ 10.,  10.,  10.,  10.,  10.],
       [ 11.,  11.,  11.,  11.,  11.]])

In [148]:
array1[[-1]]

array([[ 11.,  11.,  11.,  11.,  11.]])

In [149]:
array1[[-2,-4]]

array([[ 10.,  10.,  10.,  10.,  10.],
       [  8.,   8.,   8.,   8.,   8.]])

In [150]:
array2 = np.arange(40).reshape((8,5))

In [151]:
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [152]:
array2[[1,2],[0,1]]

array([ 5, 11])

In [ ]:
# 27, 33, 39   27 = (5,2)  33 = (6,3) 39 = (7,4)

In [153]:
array2[[5,6,7],[2,3,4]]

array([27, 33, 39])